image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - test

test:
    stage: test
    script: 
        - "cd avg_word_length.Tests"
        - "dotnet test"
        - "cd .."
        - "cd avg_word_length.IntegrationTests"
        - "dotnet test"